### ISSUE TITLE
VSCode extension results in NoClassDefFoundError for HelpList

### ISSUE THREAD

**Issue by smyalygames** [nickbattle/vdmj#72]
The 4.5.0-SNAPSHOT does not run on VSCode and VSCodium with `overturetool.vdm-vscode-1.3.7-patch.vsix` it seems that `HelpList` is not present. However, it works fine with `vdmj-suite-4.5.0-P-SNAPSHOT-231130-distribution.zip` and `vdmj-suite-4.5.0-SNAPSHOT-231203-distribution.zip`.

It also seems that the MD5 checksums for the jars included in the VSIX are the same.

**settings.json config:**
```json
"vdm-vscode.server.plugins": [
        {
            "classname": "quickcheck.plugin.QuickCheckLSPPlugin",
            "dialects": [ "vdmsl", "vdmpp", "vdmrt" ],
            "jar": "~/.vscode-oss/extensions/overturetool.vdm-vscode-1.3.7/resources/jars/plugins/quickcheck-4.5.0-SNAPSHOT.jar",
            "name": "QuickCheck Plugin"
       }
    ],
```

**Error Logs:**
```
Exception in thread "LSP Listener" 
java.lang.NoClassDefFoundError: vdmj/commands/HelpList
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3557)

	at java.base/java.lang.Class.getMethod0(Class.java:3529)
	at java.base/java.lang.Class.getMethod(Class.java:2225)
	at workspace.LSPXWorkspaceManager.enablePlugins(LSPXWorkspaceManager.java:121)
	at workspace.LSPWorkspaceManager.lspInitialize(LSPWorkspaceManager.java:209)
	at lsp.InitializeHandler.initialize(InitializeHandler.java:76)
	at lsp.InitializeHandler.request(InitializeHandler.java:51)
	at rpc.RPCDispatcher.dispatch(RPCDispatcher.java:69)
	at lsp.LSPServer.run(LSPServer.java:161)

	at lsp.LSPServerSocket.run(LSPServerSocket.java:121)
	at lsp.LSPServerSocket.main(LSPServerSocket.java:101)
Caused by: java.lang.ClassNotFoundException: vdmj.commands.HelpList

	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 14 more
```

**Comment by nickbattle** [comment]
Hmm... The HelpList class usage was changed recently. That class should come from  the VDMJ jar. I have been updating the distributions and VSIX very frequently over the past couple of weeks, so it's possible that you picked up a version that was half way through being complete? Curious though, if the checksums are the same. It does work here...

Does it fail immediately on startup or on opening a console or asking for help or...?

https://github.com/nickbattle/vdmj/releases/download/4.5.0-1/overturetool.vdm-vscode-1.3.7.vsix

**Comment by nickbattle** [comment]
Peter had the same problem. I think it's because your QuickCheck plugin configuration is pointing to a location that is not within the VSIX installed content, and so is not the latest version.

Can you confirm that the "~/vscode-oss" location ini settings is where the VSIX jars are installed? I'm also not sure whether the "~" expansion works here. I usually use a full explicit path, like "/home/nick/.vscode/extensions..."

**Comment by nickbattle** [comment]
It turns out, it was the Isabelle plugin that was out of date in the VSIX, sorry for the confusion. The latest VSIX (same URL) excludes Isabelle until we can get this rebuilt.

**Comment by nickbattle** [comment]
Can we close this now?

**Comment by smyalygames** [comment]
Hiya, sorry for not responding, I was really busy with exams.

But I just tested this now and it works perfectly fine :)

Thank you for fixing this!
